/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BKBadge: typeof import('./components/BKBadge.vue')['default']
    BKButton: typeof import('./components/BKButton.vue')['default']
    BKDateSelector: typeof import('./components/BKDateSelector.vue')['default']
    BKIconButton: typeof import('./components/BKIconButton.vue')['default']
    EventCard: typeof import('./components/EventCard.vue')['default']
    EventFilter: typeof import('./components/EventFilter.vue')['default']
    EventMap: typeof import('./components/EventMap.vue')['default']
    FlashBanner: typeof import('./components/FlashBanner.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
